### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by sparshgarg23** [matssteinweg/Multi-Purpose-MPC#1]
the file sim_map.png and real_map.png are missing.
Are these images automatically saved by the code?

**Comment by Shantnu12345** [comment]
Facing the same issues. Unable to run this code because sim_map.png is not available. It would be great to have it.

**Comment by matssteinweg** [comment]
Hi guys, 

you're right, the files are missing. It seems we forgot to include them when preparing the repository for the public release.
I'm currently fixing the issue and will update the repo later today.
Please have a look then and let me know if you encounter any other problems.

Best, 
Mats

**Comment by matssteinweg** [comment]
I just added the map files. If you pull the latest version and run `simulation.py` you should see a simulation similar to the GIF displayed in the readme.

Let me know if you have any further questions.
Best, Mats

**Comment by sparshgarg23** [comment]
Sure ,thanks .

    On Thursday, 13 August, 2020, 9:29:03 pm IST, Mats Steinweg <notifications@github.com> wrote:  
 
 


I just added the map files. If you pull the latest version and run simulation.py you should see a simulation similar to the GIF displayed in the readme.

Let me know if you have any further questions.
Best, Mats
