### ISSUE TITLE
Consideration of max steer angle

### ISSUE THREAD

**Issue by Shantnu12345** [matssteinweg/Multi-Purpose-MPC#2]
Hi,

Thank you for making this open source. It is very helpful for the reseachers :)

I tried goining through the bicycle model code, however, I couldnot find any input for max steering angle of the vehicle. May be I missed it. Could you please verify if maximum steering angle of the vehicle is being considered or not in generating the paths?

Best,
Shantnu

**Comment by matssteinweg** [comment]
Hi Shantnu,

there is no maximum steering angle for the bicycle model. The maximum steering is modelled as an input constraint of the MPC problem and is thus handled outside of the model. Please have a look at `simulation.py` where we specify the input constraints for the MPC. 
I hope this answers your questions. If you have further questions, please don't hesitate to contact me.

Best, 
Mats

**Comment by Shantnu12345** [comment]
Thank you. That answers my question.
